openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-asa9.onrender.com/api/v1
paths:
  /contacts:
    get:
      $ref: ../docs/swagger/paths/contacts/get.yaml
    post:
      $ref: ../docs/swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../docs/swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../docs/swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../docs/swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../docs/swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../docs/swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../docs/swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../docs/swagger/paths/auth/refresh/post.yaml
  /auth/send-reset-email:
    post:
      $ref: ../docs/swagger/paths/auth/send-reset-email/post.yaml
  /auth/reset-pwd:
    post:
      $ref: ../docs/swagger/paths/auth/reset-pwd/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
